baseURL = "https://example.com/"
theme = "salinger"
title = "salinger"
copyright = '2001 John Doe'
ignoreErrors = ["error-remote-getjson"]

[params]
header = "<strong>Hey there!<br/>I'm Purnima 👋</strong>"
keywords = [ "Portfolio", "developer", "coding", "maker"]
showHeaderOnHomepage = false
#googleAnalytics = ""
twemoji = true
text404 = "Since the page you were looking for seems like doesn't exist, we <strong>strongly</strong> suggest you to better investigate the URL and/or go back to the <a href=\"/\">home</a>. </br></br> <iframe src=\"https://giphy.com/embed/aCKMaeduKfFXG\" width=\"480\" height=\"480\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen></iframe>"
#fontawesomekitcode = ""


[permalinks]
  '/' = '/:slug/'
  'projects' = '/:slug/'

[[params.social]]
name = "telegram"
url = "https://t.me/zxzxzchu"
icon = "fa fa-telegram"
before = ""

[[params.social]]
name = "github"
url = "https://github.com/saipurnimag"
icon = "fa fa-github"
before = ""

[[params.social]]
name = "email"
icon = "fa fa-envelope-o"
url = "mailto:saipurnima@outlook.com"
before = ""

[[params.social]]
name = "instagram"
icon = "fa fa-instagram"
url = "https://www.instagram.com/_purnima.g_/"
before = ""




[Menu]
[[Menu.Main]]
name = "Projects."
url = "/projects/"
weight = 1

[[Menu.Main]]
name = "Contact me."
url = "mailto:mail@mail.com"
weight = 2

[taxonomies]
	tag = "tags"
	category = "categories"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true